/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "calcula.h"

int add(CLIENT* clnt, int x, int y) {
    operandos ops;
    int* result = NULL;
    ops.x = x;
    ops.y = y;
    result = add_100(&ops, clnt);
    if (result == NULL) {
        fprintf(stderr, "Erro na chamada RPC da função add().");
        exit(0);
    }
    return *result;
}

int sub(CLIENT* clnt, int x, int y) {
    operandos ops;
    int* result = NULL;
    ops.x = x;
    ops.y = y;
    result = sub_100(&ops, clnt);
    if (result == NULL) {
        fprintf(stderr, "Erro na chamada RPC da função sub().");
        exit(0);
    }
    return *result;
}

int main (int argc, char *argv[]) {
    CLIENT* clnt;
    int x = 0, y = 0;
    if (argc != 4) {
        fprintf(stderr, "usage: %s <hostname> <num1> <num2>\n", argv[0]);
        exit(0);
    }
    clnt = clnt_create(argv[1], PROG, VERSAO, "udp");
    if (clnt == (CLIENT *)NULL) {
        clnt_pcreateerror(argv[1]);
        exit(0);
    }
    x = atoi(argv[2]);
    y = atoi(argv[3]);
    printf("%d + %d = %d\n", x, y, add(clnt, x, y));
    printf("%d - %d = %d\n", x, y, sub(clnt, x, y));
    return 0;
}
